MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.fpn_ResNet101_conv5_body
  FASTER_RCNN: True
  MASK_ON: True
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  BASE_LR: 0.01
  GAMMA: 0.1
  MAX_ITER: 180000
  STEPS: [0, 120000, 160000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: '/home/stevenwudi/PycharmProjects/mask-rcnn.pytorch/data/pretrained_model/X-101-32x8d.pkl'
  STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
  TRANS_FUNC: bottleneck_transformation
  NUM_GROUPS: 32
  WIDTH_PER_GROUP: 8
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
MRCNN:
  ROI_MASK_HEAD: mask_rcnn_heads.mask_rcnn_fcn_head_v1up4convs
  RESOLUTION: 28  # (output mask resolution) default 14
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14  # default 7
  ROI_XFORM_SAMPLING_RATIO: 2  # default 0
  DILATION: 1  # default 2
  CONV_INIT: MSRAFill  # default GaussianFill
TRAIN:
  SCALES: (1200, 1300, 1400, 1500)
  # SCALES: (1700, 1900, 2100, 2300, 2500, 2710) # Train will randomly choose one of the scale
  RANDOM_CROP: 0
  MAX_SIZE: 1500
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  SNAPSHOT_ITERS: 3000
  #CE_FINETUNE_WIGHT: (12.93827403, 36.95162347, 26.24456702,  1. , 18.74950147,3.17959082, 22.5259255)
  #CE_FINETUNE_WIGHT: (   5,     35,        26,            1. ,    10,        3,         20)
                    # '__background__', bus', 'tricycle', 'motorcycle', 'car', 'truck', 'pedestrian', 'bicycle'
  CE_FINETUNE_WIGHT: ( 1,  1.20,    6.4,         14.35,      1.   , 2.48,   1.53427976,    4.088)

TEST:
  SCALE: 0  # 2710
  MAX_SIZE: 3384  # 3384
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  RPN_POST_NMS_TOP_N: 2000  # 1000 default
  BBOX_VOTE:
    ENABLED: True
    VOTE_TH: 0.9
  BBOX_AUG:
    ENABLED: True
    SCORE_HEUR: UNION
    COORD_HEUR: UNION
    H_FLIP: True
    SCALES: (1700, 1900, 2100, 2300, 2500, 2710)
    MAX_SIZE: 3384
    SCALE_H_FLIP: True
    SCALE_SIZE_DEP: False
    ASPECT_RATIOS: ()
    ASPECT_RATIO_H_FLIP: False
  MASK_AUG:
    ENABLED: True
    HEUR: SOFT_AVG
    H_FLIP: True
    SCALES: (1700, 1900, 2100, 2300, 2500, 2710)
    MAX_SIZE: 2000
    SCALE_H_FLIP: True
    SCALE_SIZE_DEP: False
    ASPECT_RATIOS: ()
    ASPECT_RATIO_H_FLIP: False
